//
//  Printable.swift
//  SwiftPoet
//
//  Created by Kyle Dorman on 1/25/16.
//
//

import Foundation

public protocol PoetPrintable {
    func toFile() -> String

    func createdAt() -> String

    func generatedByAt() -> String
}

extension PoetPrintable {
    public func createdAt() -> String {
        let formatter = NSDateFormatter()
        formatter.dateStyle = .ShortStyle
        return formatter.stringFromDate(NSDate())
    }

    public func generatedByAt() -> String {
        return "Generated by SwiftPoet on \(createdAt())"
    }
}
